diff --git a/Makefile b/Makefile
index 20182a2..e6f5739 100644
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,4 @@
-CFLAGS		= -g -O3 -Wall -Wextra
+CFLAGS		= -g -O3 -Wall -Wextra -pthread
 LINKFLAGS	= -lpthread
 
 DESTDIR		=
