Document: mdk3
Title: Debian mdk3 Manual
Author: <insert document author here>
Abstract: This manual describes what mdk3 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mdk3/mdk3.sgml.gz

Format: postscript
Files: /usr/share/doc/mdk3/mdk3.ps.gz

Format: text
Files: /usr/share/doc/mdk3/mdk3.text.gz

Format: HTML
Index: /usr/share/doc/mdk3/html/index.html
Files: /usr/share/doc/mdk3/html/*.html
